
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tquqmhjxjpaksnizcnjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdXFtaGp4anBha3NuaXpjbmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTg2MDQsImV4cCI6MjA2MzE5NDYwNH0.I44vwhIJnTdHFnGcbv90-MiuHnMPZmZaDcnqeHEineM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
